services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=statistics
      - POSTGRES_USER=statistics
      - POSTGRES_DB=statistics
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewmmainadmin
      - POSTGRES_USER=ewmmainadmin
      - POSTGRES_DB=ewmmain
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  stats-server:
    build: ./ewm-stats/stats-server
    image: ewm-stats
    container_name: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=statistics
      - SPRING_DATASOURCE_PASSWORD=statistics
  ewm-service:
    build: ./ewm-main
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATISTICS_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmmain
      - SPRING_DATASOURCE_USERNAME=ewmmainadmin
      - SPRING_DATASOURCE_PASSWORD=ewmmainadmin